### ISSUE TITLE
[Bug] Leaderboard profile detail has an off by one error.

### ISSUE THREAD

**Issue by CumpsD** [iron-fish/website-testnet#130]
When looking at the leaderboard for Total Points we see the following:

![image](https://user-images.githubusercontent.com/1201644/144325026-740fb18b-9baf-4f61-8569-d573f5193d2d.png)

When we view the detail of the user, we notice user in rank `1st` is `2nd` on his detail page.

![image](https://user-images.githubusercontent.com/1201644/144324988-effdd079-6839-4902-99e0-29aef3cd0d93.png)

Same for the 2nd user his detail page:

![image](https://user-images.githubusercontent.com/1201644/144325121-0b705193-5d9b-4cce-919b-f21448e8dc56.png)

**Comment by dguenther** [comment]
Actually, this might be a separate issue since it happened before the testnet week rolled over. It'll probably be clearer to debug after looking at the other issue.

**Comment by CumpsD** [comment]
Yes, it's a bug from the first week :)

**Comment by dguenther** [comment]
To clarify this specific issue, the ranks on the leaderboard list do not match up with the ranks shown on the user profile pages.

**Comment by dguenther** [comment]
At this point, we've fixed all known issues with the ranks on the leaderboard differing from the ranks on the user profiles. Let us know if you see any other issues!
