### ISSUE TITLE
Leaderboard user details page is not displayed correctly on mobile device (iphone)

### ISSUE THREAD

**Issue by cyberguy85** [iron-fish/website-testnet#135]
When using leaderboard page on mobile device (iPhone 12 pro) in Chrome browser the user details page is not displayed correctly. Most of the important information is cut and is not scrollable. Please see a screenshot attached.
![IMG_6421](https://user-images.githubusercontent.com/68616601/145585424-f29d41c3-f4e1-43d9-8af2-9503d2874626.jpg)

**Comment by psevdokounian** [comment]
Same and not only user details. List in the leaderboad looking not good too. Android. Samsung.

![image](https://user-images.githubusercontent.com/55825515/146335368-2a2afec3-f20f-486c-b2ba-6ac29031d02a.png)
![image](https://user-images.githubusercontent.com/55825515/146335446-f1df046d-b4be-4c88-865a-cbc15179248c.png)
![image](https://user-images.githubusercontent.com/55825515/146335472-e40e458b-ed81-43e6-982b-db046b77b9ab.png)
![image](https://user-images.githubusercontent.com/55825515/146335489-9c72d186-a99f-4db0-9d99-203ae6987707.png)
![image](https://user-images.githubusercontent.com/55825515/146335513-b3fb3660-eba0-41e8-a6ca-4999bf581dac.png)
![image](https://user-images.githubusercontent.com/55825515/146335540-685f3f35-4624-4aa9-959b-930705b58f90.png)
![image](https://user-images.githubusercontent.com/55825515/146335555-324d52e8-affb-4698-b895-39fc764d3b54.png)

**Comment by manjash** [comment]
@dguenther  Hey, I hope you don't mind if I try to fix the issue?

**Comment by dguenther** [comment]
Let me check if we have any design mock-ups for this first. But no one's actively working on it now so it'd be okay to pick up!

**Comment by dguenther** [comment]
@manjash This is what we have for mockups for mobile -- I think the user details and the main leaderboard page could be split into two separate PRs. The implementation doesn't have to be exactly the same if it's not convenient to implement, but the closer the better! Feel free to post on this issue if you have questions.

![image](https://user-images.githubusercontent.com/767083/150015956-19fb0208-9a26-4869-87c4-adec64957989.png)

![image](https://user-images.githubusercontent.com/767083/150016414-327ccad5-58f1-4415-ab69-04859a71c621.png)

**Comment by manjash** [comment]
@dguenther Awesome! Thank you for the mocks, looks really good )))) I'll let you know about the progress ))

**Comment by wd021** [comment]
@manjash are you still working on this? haven't noticed any updates on your end in your latest PRs.

Lmk if you're still active with this, otherwise I'll look to pick this up.

**Comment by manjash** [comment]
Hey, yep, I got a bit distracted, I plan to finish it soon (mb in a day or 2). Sorry for the wait.

**Comment by wd021** [comment]
great, no worries.

**Comment by AmberKiso** [comment]
Validated I can scroll an individual profile and the leaderboard displays correctly on an Android phone, Chrome and Firefox.
So I think we can close this ticket.

**Comment by dguenther** [comment]
Yep, let's close it! If you run into more issues with the website on mobile, feel free to open additional issues.
