### ISSUE TITLE
How do I find my graffiti?

### ISSUE THREAD

**Issue by lutianxiong** [iron-fish/website-testnet#150]
registered, but I forgot to graffiti...

**Comment by dguenther** [comment]
When you log in to the testnet website, you should see your graffiti appear in a bubble in the top right where the "Login" text was previously.

**Comment by lutianxiong** [comment]
> When you log in to the testnet website, you should see your graffiti appear in a bubble in the top right where the "Login" text was previously.

After I logged in, the login text was still displayed in the top right corner, and when I logged in again, it said I was logged in, and nothing changed in the top right corner.

Is this a bug?

**Comment by lutianxiong** [comment]
console->network-> **[ https://api.ironfish.network/me]( https://api.ironfish.network/me)** -> 401 Unauthorized
