### ISSUE TITLE
website signup not working 

### ISSUE THREAD

**Issue by ezioruan** [iron-fish/website-testnet#151]
I have signup a user by the email `qiaoqinqie2@gmail.com`
however, after that, I can't log in, the screen keeps asking me the email address, Please fill out all fields
see the screenshot below
![image](https://user-images.githubusercontent.com/631411/144812704-75d69546-b33a-4804-9581-8a9aeac301cf.png)

**Comment by dguenther** [comment]
We've redone our signup process since this issue was created, so this should no longer be an issue, but please reopen the issue if you're still having this problem.
