### ISSUE TITLE
Leaderboard point bug

### ISSUE THREAD

**Issue by brahitoz** [iron-fish/website-testnet#157]
the place where the information is taken on whether the block will be paid or not does not coincide with the place where the information is taken from when specifying the number of aligned blocks for this week. 
Therefore, the information in the leaderboard does not correspond to each other
![InkedСкриншот 09-12-2021 060621_LI](https://user-images.githubusercontent.com/81829973/145348407-5fcc747d-ade0-49b7-9867-d62eeb11587e.jpg)

**Comment by dguenther** [comment]
We've fixed all known cases where the leaderboard ranks and values don't match up with those on the user profile, as well as when weekly points weren't calculated correctly.

In this case, you're viewing the "All Time Stats" tab, which shows points earned during the entire testnet, as well as blocks mined that didn't earn points. So it may show 13 blocks mined, but only some of them are eligible for points during a particular week.
