### ISSUE TITLE
Leaderboard mobile compatibility

### ISSUE THREAD

**Issue by j43li** [iron-fish/website-testnet#171]
### What happened?

Leaderboard doesn't show properly in mobile browser.

**Comment by leanthebean** [comment]
https://github.com/iron-fish/ironfish/issues/703

**Comment by wd021** [comment]
i'm on it. will fix this.

**Comment by wd021** [comment]
fixed here - https://github.com/iron-fish/website-testnet/pull/187

**Comment by AmberKiso** [comment]
Agreed with issue resolved, at least on Android.

**Comment by dguenther** [comment]
Agreed, this looks good! I'll close the issue, and if we're seeing more mobile issues on the latest version, feel free to open additional issues.
