### ISSUE TITLE
Testnet Leaderboard mobile sizing is broken

### ISSUE THREAD

**Issue by sternhenri** [iron-fish/website-testnet#184]
I am seeing the following on mobile (iOS in Safari, Firefox, Chrome). Namely, some of the website resizing for mobile compresses the points together with the usernames making it especially hard to understand when usernames end in digits. 

![IMG_3019](https://user-images.githubusercontent.com/3359083/152854717-41988b1d-cf15-4e80-987a-e625057df4a5.PNG)

**Comment by AmberKiso** [comment]
Validated the leaderboard displays correctly on an Android phone, Chrome and Firefox.
If someone validates on Safari, I think we can close this.

**Comment by dguenther** [comment]
I can validate this works on Safari mobile. I'll close this for now, and if anyone runs into mobile issues on the updated version, feel free to open new issues to address those. Glad to get this addressed!
