### ISSUE TITLE
'Weekly Points' on Widescreen

### ISSUE THREAD

**Issue by wd021** [iron-fish/website-testnet#204]
`Weekly points` stays on 1 line when the width is wide. Then if you make it extra-wide, it goes to a 2nd line.

![Screenshot 2022-03-08 at 20 07 18](https://user-images.githubusercontent.com/2752586/157316508-9489f17c-a711-49ab-9aaa-e83761e4c443.png)
![Screenshot 2022-03-08 at 20 07 25](https://user-images.githubusercontent.com/2752586/157316502-0efd2466-adc8-4688-b599-d7e327d15b21.png)

**Comment by brekk** [comment]
@wd021 Good catch. I saw this recently as well. Will address soonish.

**Comment by brekk** [comment]
@wd021 This fix should be on `master` shortly, LMK if this addresses it.

**Comment by wd021** [comment]
@brekk yup looks great. 👍

**Comment by dguenther** [comment]
Great, I'll close this -- thanks for reporting it!
