### ISSUE TITLE
Misaligned text in "Win a Category..." section

### ISSUE THREAD

**Issue by AmberKiso** [iron-fish/website-testnet#221]
Noticed the text body is left-justified and not centered in the "Win a Category, win an NFT!" section on https://testnet.ironfish.network/about
Shows up on Windows/Firefox and Win/Edge
![image](https://user-images.githubusercontent.com/96642073/161899065-bf1b24cb-6b9e-4f41-b2d6-35cbcbf317a5.png)

**Comment by AmberKiso** [comment]
Looks like this was introduced in PR #196 but fixed with #219.
(#220 also has this symptom.)

**Comment by dguenther** [comment]
Good spot, thanks! I'm glad we incidentally fixed it in #219 😄

**Comment by AmberKiso** [comment]
Should have closed this earlier, so doing it now.
