### ISSUE TITLE
Phase 1 leaderboard pages-by-ranks broken

### ISSUE THREAD

**Issue by AmberKiso** [iron-fish/website-testnet#265]
On Windows 10/Firefox, the phase 1 leader board does not show the correct order of participants in the Bugs caught, PRs landed, and Promotion categories after the first page.

First page for Promotions:
![image](https://user-images.githubusercontent.com/96642073/168520326-9040359f-b534-400a-b6fc-7fbd7e783b9a.png)

The page after pressing `Next >>` once:
![image](https://user-images.githubusercontent.com/96642073/168520426-ede22a8f-8b4d-4df9-a586-36d3960c4f02.png)

I'd expect the page to show ranks 26 through 50.

**Comment by wd021** [comment]
fixed now
