### ISSUE TITLE
log in fail infinity veryfifcation

### ISSUE THREAD

**Issue by qwewer303** [iron-fish/website-testnet#415]
I have already logged in my account, but the button in the right top still showes "login".
When I click any button, the right top button always showes "login" again.

https://github.com/iron-fish/website-testnet/issues/148

I couldn't solve the problem with the solution in this link.
Please tell me another solution.
I have tried more than 20 times but it keeps asking me to verify my mail.

**Comment by dguenther** [comment]
Please create a support ticket on Discord for this if you need help.
