### ISSUE TITLE
Non working portal from Russian IP

### ISSUE THREAD

**Issue by BrainCord** [iron-fish/website-testnet#421]
Hi there! Portal http://testnet.ironfish.network/ have a problems in the sections: 
1. https://testnet.ironfish.network/login
2. https://testnet.ironfish.network/about
3. https://testnet.ironfish.network/leaderboard
4. https://testnet.ironfish.network/faq
![image](https://user-images.githubusercontent.com/60858072/224011674-bdc75420-9e5e-4f2e-a956-e63e7c784277.png)
**Infinity download**, if we enable VPN and switch country from Russian Federation IP to any, all work fine. Please fix it!

**Comment by dguenther** [comment]
If you need to access your account, you can file a support ticket in Discord. Otherwise, we suggest using a VPN if you're not able to access the site.
